global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'finagent-monitor'

scrape_configs:
  # FastAPI Application Metrics
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # Node Exporter (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Celery Worker Metrics
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-worker:5555']
